# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 44ab834ae683a3dbd076b8e9e077c99c14d5a5868634f847432a55e8ee6d877ca1ac020e67f20ad7298e8d96d0018c8a75b81c386a94e3025426cc0f0e5e0962

test:
  domain_name: example.com 
  secret_key_base: 150a58bf6e9a5800864ba356a52afc4f042f2d5f569d72afda9f638a96a7e97f8d02a85133abd75c44172e13377645115e02c4cfe662e8de53191b339b42548b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
